### ISSUE TITLE
Rey's last name on 1000 soils study landing page is spelled wrong

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#956]
I think we can fix this with change sheets?

<img width="759" alt="Screen Shot 2023-04-21 at 1 11 42 PM" src="https://user-images.githubusercontent.com/44581429/233726227-0cc9ee5b-d2d3-4a4e-8317-9e6f6bd611dd.png">
<img width="466" alt="Screen Shot 2023-04-21 at 1 11 22 PM" src="https://user-images.githubusercontent.com/44581429/233726234-06e97e45-bea0-4886-8222-d9cef418bc6f.png">

**Comment by naglepuff** [comment]
Just checked with the study data in MongoDB. I don't see an accent there, so changesheet + ingest should be the next step for solving this.

**Comment by aclum** [comment]
@mslarae13  did you fix your API access?

**Comment by mslarae13** [comment]
@ssarrafan  nope. I will provide a change sheet.

**Comment by aclum** [comment]
This is fixed in mongo prod. Requires ingest to data portal prod.

**Comment by ssarrafan** [comment]
Still needs ingest, moving to next sprint.

**Comment by mslarae13** [comment]
@naglepuff  just checked dev, looks great! Good to ingest into prod!

**Comment by naglepuff** [comment]
Ingest to production is complete. Closing this issue.

**Comment by mslarae13** [comment]
@naglepuff  ... Rey's name is still wrong on prod
![Screen Shot 2023-07-07 at 12 55 51 PM](https://github.com/microbiomedata/nmdc-server/assets/44581429/14903260-53cf-4ff0-bbb6-f10444fc88a1)

**Comment by naglepuff** [comment]
I may have forgotten to point the data portal to the correct database. I just made the switch, it should appear in prod soon, if you don't see it already.
